"""
Path: config/constants.py
說明：集中定義專案共用固定常數與狀態值，避免各模組自行硬寫字串。
"""

# engine_mode
ENGINE_MODE_BACKTEST = "BACKTEST"
ENGINE_MODE_REALTIME = "REALTIME"

ENGINE_MODES = {
    ENGINE_MODE_BACKTEST,
    ENGINE_MODE_REALTIME,
}

# trade_mode
TRADE_MODE_TESTNET = "TESTNET"
TRADE_MODE_LIVE = "LIVE"

TRADE_MODES = {
    TRADE_MODE_TESTNET,
    TRADE_MODE_LIVE,
}

# trading_state
TRADING_STATE_ON = "ON"
TRADING_STATE_ENTRY_FROZEN = "ENTRY_FROZEN"
TRADING_STATE_OFF = "OFF"

TRADING_STATES = {
    TRADING_STATE_ON,
    TRADING_STATE_ENTRY_FROZEN,
    TRADING_STATE_OFF,
}